server:
  port: 8081
  shutdown: graceful
logging:
  level:
    "liquibase" : info
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/liquibaseTest?useSSL=false
    username: root
    password: "123456!!"
  cloud:
    function:
      definition: printMessage;printHello
    stream:
      bindings:
        printMessage-in-0:
          destination: topicMessage
          group: consumer-topicMessage
        printMessage-out-0:
          destination: topicMessage
        printHello-in-0:
          destination: topicHello
          group: consumer-topicHello
        printHello-out-0:
          destination: topicHello

      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          printMessage-in-0:
            consumer:
              broadcasting: true
          printHello-in-0:
            consumer:
              broadcasting: true

  liquibase:
    enabled: true
    contexts: local
